- name: check if lua-language-server binary exists
  stat:
    path: /home/{{ username }}/.local/lsp/lua-language-server/bin/lua-language-server
  register: lua_binary_stat

- block:
    - name: Create directory if it does not exist
      become_user: '{{username}}'
      file:
        path: '/home/{{ username }}/.local/lsp/lua-language-server'
        state: directory

    - name: download lua-language-server tar
      become_user: '{{username}}'
      get_url:
        url: 'https://github.com/LuaLS/lua-language-server/releases/download/3.7.4/lua-language-server-3.7.4-linux-x64.tar.gz'
        dest: /home/{{username}}/.local/lsp/lua-language-server/lua-language-server-3.7.4-linux-x64.tar.gz
        group: '{{username}}'
        owner: '{{username}}'
        mode: '0644'

    - name: Unzip lua-language-server tar.gz
      become_user: '{{username}}'
      unarchive:
        src: '/home/{{ username }}/.local/lsp/lua-language-server/lua-language-server-3.7.4-linux-x64.tar.gz'
        dest: '/home/{{ username }}/.local/lsp/lua-language-server'
        remote_src: yes
        creates: '/home/{{ username }}/.local/lsp/lua-language-server/bin/lua-language-server'

    - name: Change permissions of lua-language-server binary
      file:
        path: '/home/{{ username }}/.local/lsp/lua-language-server/bin/lua-language-server'
        mode: '0755'

    - name: Copy lua-language-server wrapper script to .local/bin
      ansible.builtin.copy:
        src: ./lua-language-server
        dest: /home/{{ username }}/.local/bin/
        mode: '0755'

  when: not lua_binary_stat.stat.exists

- name: Check if stylua is already installed
  become_user: '{{username}}'
  shell:
    cmd: 'zsh -c "source ~/.zshrc; command -v stylua >/dev/null 2>&1"'
  register: stylua_installed
  ignore_errors: true
  changed_when: false

- name: Install stylua using cargo
  become_user: '{{username}}'
  shell:
    cmd: 'zsh -c "source ~/.zshrc; cargo install stylua"'
  args:
    creates: ~/.cargo/bin/stylua
  changed_when: False
  when: stylua_installed.rc != 0
