- name: Define golang packages
  set_fact:
    go_packages:
      - name: golang.org/x/tools/gofmt
        version: latest
        test: gofmt
      - name: golang.org/x/tools/gopls
        version: latest
        test: gopls
      - name: github.com/go-delve/delve/cmd/dlv
        version: latest
        test: dlv
      - name: github.com/google/gops
        test: gopls
        version: latest

- name: 'check if go packages are installed'
  become_user: '{{username}}'
  shell:
    cmd: 'zsh -c "source ~/.zshrc; {{item.test}}"'
  loop: '{{ go_packages }}'
  changed_when: false
  failed_when: false
  register: package_show_installed
  loop_control:
    index_var: index

- name: Debug package_show_installed.rc
  debug:
    msg: "{{ item.name }} check if installed: {{ 'yes' if package_show_installed.results[index].rc == 0 else 'no' }}"
  loop: '{{ go_packages }}'
  loop_control:
    index_var: index

- name: Install golang packages
  become_user: '{{username}}'
  shell: >
    {% if item.version is defined  %}
    zsh -c "source ~/.zshrc; go install {{item.name}}@{{item.version}}"
    {% else %}
    zsh -c "source ~/.zshrc; go install {{item.name}}@latest"
    {% endif %}
  register: package_install
  failed_when: package_install.rc != 0
  when: package_show_installed.results[index].rc != 0
  loop: '{{ go_packages }}'
  loop_control:
    index_var: index
