- name: check go is installed
  become_user: '{{username}}'
  shell: 'zsh -c "source ~/.zshrc; command -v go"'
  register: go_command_check
  changed_when: false
  failed_when: false

- block:
  - name: install go if not installed
    import_tasks: install_go.yml

  # - name: install go packages
  #   import_tasks: install_go_packages.yml
  when: go_command_check.rc != 0

# ! I do not trust this at the moment,
# ! re-evaluating what this is for and how to make it better
# golangci-lint
# - name: copy install golangci-lint script
#   copy:
#     src: ./install-golangci-lint.zsh
#     dest: /home/{{username}}/.local/bin
#     owner: '{{username}}'
#     group: '{{username}}'
#     mode: 0755
#
# - name: install golangci-lint
#   become_user: '{{username}}'
#   shell:
#     cmd: /home/{{username}}/.local/bin/install-golangci-lint.zsh
#     creates: /home/{{username}}/.local/go/bin/golangci-lint
