- name: install packages
  apt:
    update_cache: yes
    pkg:
      - lua5.1

- name: Define Luarocks packages
  set_fact:
    luarocks_packages:
      - name: inifile
        state: present
      - name: luafilesystem
        state: present
      - name: lyaml
        state: present

- name: Check if {{ item.name }} is installed
  shell:
    cmd: luarocks show {{ item.name }}
  register: package_show_installed
  changed_when: false
  failed_when: false
  loop: '{{ luarocks_packages }}'

- name: Debug package_show_installed.rc
  debug:
    msg: "{{ item.name }} check if installed: {{ 'yes' if package_show_installed.results[index].rc == 0 else 'no' }}"
  loop: '{{ luarocks_packages }}'
  loop_control:
    index_var: index

- name: Install Luarocks package {{ item.name }}
  shell:
    cmd: luarocks install {{ item.name }}
  register: package_install
  failed_when: package_install.rc != 0
  changed_when: "item.name + ' is now installed in' in package_install.stdout"
  when: package_show_installed.results[index].rc != 0
  loop: '{{ luarocks_packages }}'
  loop_control:
    index_var: index
