# ==================================================================================================
# This role assumes that you are using the lsp setup referenced below
# https://github.com/RolandWarburton/nvim.conf/blob/master/doc/lsp_install.txt
# ==================================================================================================

# typescript
- name: install typescript package
  become_user: '{{username}}'
  community.general.npm:
    name: typescript
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

- name: install typescript-language-server package
  become_user: '{{username}}'
  community.general.npm:
    name: typescript-language-server
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

- name: install eslint_d package
  become_user: '{{username}}'
  community.general.npm:
    name: eslint_d
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

- name: install prettierd package
  become_user: '{{username}}'
  community.general.npm:
    name: '@fsouza/prettierd'
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

# html css and json
- name: install html, css, and json package
  become_user: '{{username}}'
  community.general.npm:
    name: 'vscode-langservers-extracted'
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

# markdown
- name: install markdown-cli package
  become_user: '{{username}}'
  community.general.npm:
    name: 'markdownlint-cli'
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

# vale
- name: copy install vale script
  template:
    src: ./install-vale.j2
    dest: /home/{{username}}/.local/bin/install-vale.zsh
    owner: '{{username}}'
    group: '{{username}}'
    mode: 0755

- name: install vale
  become_user: '{{username}}'
  shell:
    cmd: /home/{{username}}/.local/bin/install-vale.zsh
    creates: /home/{{username}}/.local/bin/vale
  register: vale

# lua
- name: install ninja-build
  apt:
    update_cache: yes
    name: ninja-build

- name: clone lua lsp
  become_user: '{{username}}'
  git:
    repo: https://github.com/sumneko/lua-language-server
    depth: 1
    track_submodules: yes
    recursive: yes
    dest: /home/{{username}}/.local/lsp/lua-language-server
    accept_hostkey: yes
    key_file: /home/{{username}}/.ssh/id_github # on the remote host

- name: lua lsp update submodules
  become_user: '{{username}}'
  shell:
    cmd: 'git submodule update --depth 1 --init --recursive'
    chdir: '/home/{{username}}/.local/lsp/lua-language-server'
  changed_when: false # just ignore this

- name: run luamake build.sh
  become_user: '{{username}}'
  shell:
    cmd: './compile/build.sh'
    chdir: '/home/{{username}}/.local/lsp/lua-language-server/3rd/luamake'
  changed_when: false # just ignore this

- name: run luamake rebuild
  become_user: '{{username}}'
  shell:
    cmd: './3rd/luamake/luamake rebuild'
    chdir: '/home/{{username}}/.local/lsp/lua-language-server'
    creates: '/home/{{username}}/.local/lsp/lua-language-server/bin/lua-language-server'
