# ==================================================================================================
# This role assumes that you are using the lsp setup referenced below
# https://github.com/RolandWarburton/nvim.conf/blob/master/doc/lsp_install.txt
# ==================================================================================================

- name: typescript lsp
  import_tasks: typescript.yml

- name: web lsp
  import_tasks: web.yml

- name: markdown lsp
  import_tasks: markdown.yml

- name: lua lsp
  import_tasks: lua.yml
