# typescript
- name: install typescript package
  become_user: '{{username}}'
  community.general.npm:
    name: typescript
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

- name: install typescript-language-server package
  become_user: '{{username}}'
  community.general.npm:
    name: typescript-language-server
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

- name: install eslint package
  become_user: '{{username}}'
  community.general.npm:
    name: eslint
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present

- name: install prettier package
  become_user: '{{username}}'
  community.general.npm:
    name: 'prettier'
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present
