# html css and json
- name: install html, css, and json package
  become_user: '{{username}}'
  community.general.npm:
    name: 'vscode-langservers-extracted'
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{node_version}}/bin/npm
    state: present
