- name: install packages
  apt: 
    update_cache: yes
    pkg:
      - libavcodec-dev 
      - libavfilter-dev 
      - libass-dev 
      - ffmpeg
      - lua5.1

- name: ensure build dir created
  file:
    path: '{{tmp_dir}}'
    state: directory
    mode: '0755'
    owner: '{{username}}'
    group: '{{username}}'

# get repos
- name: clone mpv
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/mpv-player/mpv.git'
    dest: '{{tmp_dir}}/mpv'
    version: 'v0.35.0'
    depth: 1

- name: build mpv (configure)
  become_user: '{{username}}'
  shell:
    cmd: > 
      meson setup build
      -Dx11=disabled
      -Dwayland=enabled
      -Dpipewire=enabled
      -Dlua=lua5.1
      -Dpulse=disabled
    chdir: '{{tmp_dir}}/mpv'

- name: build mpv (compile)
  become_user: '{{username}}'
  shell:
    cmd: 'meson compile -C build'
    chdir: '{{tmp_dir}}/mpv'

- name: build mpv (install)
  shell:
    cmd: 'meson install -C build'
    chdir: '{{tmp_dir}}/mpv'
