# swww
- name: Check if build dir exists
  stat:
    path: '{{build_dir}}/swww'
  register: build_dir_exists

- name: Create build dir if it does not exist
  file:
    path: '{{build_dir}}/swww'
    state: directory
    owner: '{{username}}'
    group: '{{username}}'
  when: build_dir_exists.stat.exists == False

- name: Check if Wayland protocols directory exists
  stat:
    path: /usr/share/wayland-protocols/stable
  register: wayland_protocols_dir

- name: Fail if Wayland protocols directory does not exist
  fail:
    msg: "Wayland protocols directory /usr/share/wayland-protocols/stable does not exist! Install the wayland-protocols package."
  when: not wayland_protocols_dir.stat.exists

- name: clone swww
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/LGFae/swww.git'
    dest: '{{build_dir}}/swww'

- name: build swww (compile)
  become_user: '{{username}}'
  shell:
    cmd: 'cargo build --release'
    chdir: '{{build_dir}}/swww'
    creates: '{{build_dir}}/swww/target/release/swww'
  environment:
    WAYLAND_PROTOCOLS_DIR: /usr/share/wayland-protocols/stable

- name: Copy 'swww' binary to '/usr/bin' directory
  copy:
    src: '{{build_dir}}/swww/target/release/swww'
    dest: /usr/bin/swww
    owner: root
    group: root
    remote_src: true
    mode: 0755

- name: Copy 'swww-daemon' binary to '/usr/bin' directory
  copy:
    src: '{{build_dir}}/swww/target/release/swww-daemon'
    dest: /usr/bin
    owner: root
    group: root
    remote_src: true
    mode: 0755
