- name: Set gotify-cli architecture
  set_fact:
    gotify_cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Stat gotify binary
  stat:
    path: "{{ gotify_cli_bin_dir }}/gotify"
  register: gotify_cli_binary_stat

- name: Download gotify-cli binary
  become: true
  get_url:
    url: "https://github.com/gotify/cli/releases/download/v{{ gotify_cli_version }}/gotify-cli-linux-{{ gotify_cli_arch }}"
    dest: "{{ gotify_cli_bin_dir }}/gotify"
    owner: root
    group: root
    mode: '0755'
  when: not gotify_cli_binary_stat.stat.exists
