username: ansible
packages:
  - acl
  - git
  - ssh
  - sudo
  - curl
  - wget
  - python3
  - python3-pip
  - zsh
  - luarocks
  - build-essential
  - cmake
  - ripgrep
  - fd-find
  - htop
  - psmisc
  - fuse
  - pinentry-curses
  - pinentry-tty
