- name: Check LANG environment variable
  set_fact:
    lang_is_set: "{{ ansible_env.LANG is defined and ansible_env.LANG != '' }}"

- name: Check LANGUAGE environment variable
  set_fact:
    language_is_set: "{{ ansible_env.LANGUAGE is defined and ansible_env.LANGUAGE != '' }}"

- name: Generate locales if not already set
  when: not lang_is_set or not language_is_set
  block:
    - name: Ensure localisation files are available for '{{ config_system_locale }}'
      locale_gen:
        name: "{{ config_system_locale }}"
        state: present

    - name: Ensure localisation files are available for '{{ config_system_language }}'
      locale_gen:
        name: "{{ config_system_language }}"
        state: present
