# if the default ssh-agent.service exists then remove the X11 file requirement to start
- name: Copy ssh-agent.service to /usr/lib/systemd/user/
  copy:
    src: ssh-agent.service
    dest: /usr/lib/systemd/user/ssh-agent.service
  register: ssh_agent_condition

- name: Reload systemd daemon
  become_user: '{{username}}'
  shell:
    cmd: systemctl --user daemon-reload
  when: ssh_agent_condition.changed

- name: Enable the ssh-agent service
  become_user: '{{username}}'
  systemd:
    scope: user
    name: ssh-agent
    enabled: yes
    state: started
