- name: reload user systemd
  become: true
  become_user: "{{ username }}"
  systemd:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gotify_listener_uid.stdout | trim }}"

- name: restart gotify-listen
  become: true
  become_user: "{{ username }}"
  systemd:
    name: gotify-listen
    scope: user
    state: restarted
    enabled: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ gotify_listener_uid.stdout | trim }}"
