# Notes:
#
# you can find the name of fonts using
# fc-list | grep Hack
# fc-query <path>/HackNerdFont-Regular.ttf
#
# roles/alacritty uses this to set the terminal fonts
#

- name: install packages
  apt:
    update_cache: yes
    pkg:
      - fontconfig
      - fd-find
      - fonts-noto-color-emoji

- name: create temp directory
  file:
    path: '/tmp/ttf-hack-patched'
    mode: 0775
    state: directory

- name: download nerd fonts patched ttf-hack
  unarchive:
    src: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.tar.xz'
    dest: '/tmp/ttf-hack-patched'
    remote_src: yes

- name: create hack font directory
  file:
    path: '/usr/share/fonts/truetype/hack'
    mode: 0755
    state: directory

- name: Find ttf font files in source directory
  find:
    paths: /tmp/ttf-hack-patched
    patterns: '*.ttf'
    file_type: file
    recurse: no
  register: found_fonts

- name: Copy ttf fonts to font directory
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/truetype/hack/
    owner: root
    group: root
    mode: '0644'
  loop: "{{ found_fonts.files | map(attribute='path') | list }}"
