- name: install packages
  apt: 
    update_cache: yes
    pkg:
      - libgdk-pixbuf2.0-dev
      - meson
      - libcairo2-dev
      - libpango1.0-dev
      - wayland-protocols
      - librust-wayland-client-dev
      - flex

- name: ensure build dir created
  file:
    path: '{{tmp_dir}}'
    state: directory
    mode: '0755'
    owner: '{{username}}'
    group: '{{username}}'

# get repos
- name: clone rofi
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/lbonn/rofi.git'
    dest: '{{tmp_dir}}/rofi'
    version: 'wayland'

- name: update submodules
  become_user: '{{username}}'
  shell:
    cmd: 'git submodule update --init'
    chdir: '{{tmp_dir}}/rofi'

- name: build rofi (configure)
  become_user: '{{username}}'
  shell:
    cmd: > 
      meson setup build
      --prefix /usr
      -Dxcb=disabled
      -Dwayland=enabled
      -Dwindow=false
      -Dcheck=disabled
    chdir: '{{tmp_dir}}/rofi'

- name: build rofi (install)
  shell:
    cmd: 'sudo ninja -C build/ install'
    chdir: '{{tmp_dir}}/rofi'
