ntfy_listener_version: "1.0.0"
ntfy_listener_bin_dir: "/usr/local/bin"
ntfy_listener_download_url: "https://github.com/RolandWarburton/ntfy-listener/releases/download/v{{ ntfy_listener_version }}/ntfy-listen"
