- name: Download and install n and Node.js LTS
  shell: |
    curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | bash -s install lts
  args:
    executable: /bin/bash
    creates: /usr/local/bin/node

- name: Ensure /usr/local/bin is in PATH for all users (if needed)
  lineinfile:
    path: /etc/profile.d/n-bin-path.sh
    line: 'export PATH="/usr/local/bin:$PATH"'
    create: yes
    mode: '0755'

- name: install neovim npm package
  community.general.npm:
    name: n
    global: yes
    executable: /usr/local/bin/npm
    state: present
