- block:
    - name: install node
      become_user: '{{username}}'
      shell: 'zsh -c "source ~/.zshrc; nvm install"'
      args:
        creates: '{{ ansible_env.HOME }}/.nvm/versions/node/v{{target_node_version}}/bin/node'

    - name: symlink node to bin
      shell:
        cmd: >
          source /home/{{username}}/.zshrc;
          rm -f /usr/bin/node;
          ln -s /home/{{username}}/.nvm/versions/node/v{{target_node_version}}/bin/node /usr/bin/node;
      failed_when: false
      changed_when: false

    - name: symlink npm to bin
      shell:
        cmd: >
          source /home/{{username}}/.zshrc;
          rm -f /usr/bin/npm;
          ln -s /home/{{username}}/.nvm/versions/npm/v{{target_node_version}}/bin/npm /usr/bin/npm;
      failed_when: false
      changed_when: false
  when: node_out_of_date

# install neovim npm package if neovim is installed
- name: Check if Neovim package is installed
  ansible.builtin.command: nvim --version
  register: neovim_output
  ignore_errors: yes
  changed_when: false

- name: install neovim npm package
  become_user: '{{username}}'
  community.general.npm:
    name: neovim
    global: yes
    executable: /home/{{username}}/.nvm/versions/node/v{{target_node_version}}/bin/npm
    state: present
  when: neovim_output.rc == 0
