# zgen is a package manager for zshell (zsh) https://github.com/tarjoilija/zgen
- name: check if zgen directory exists
  stat:
    path: /home/{{username}}/.zgen
  register: zgen_stat
  tags: zgen

- name: install zgen
  become_user: '{{username}}'
  git:
    repo: https://github.com/tarjoilija/zgen.git
    dest: /home/{{username}}/.zgen
    accept_hostkey: yes
    key_file: /home/{{username}}/.ssh/id_github # on the remote host
  tags: zgen_install

- name: set users default shell to zsh
  user:
    name: '{{username}}'
    shell: '{{zsh_shell_path}}'
  tags: zgen

- name: 'run zshell to trigger zgen clone'
  become_user: '{{username}}'
  shell:
    cmd: 'zsh -i -c "source /home/{{username}}/.zshrc"'
    executable: /usr/bin/zsh
    chdir: /home/{{username}}
  tags: zgen
