# typescript
- name: set npm executable
  set_fact:
    npm_executable: /home/{{username}}/.nvm/versions/node/v{{target_node_version}}/bin/npm

- name: install typescript package
  become_user: '{{username}}'
  community.general.npm:
    name: typescript
    global: yes
    executable: '{{npm_executable}}'
    state: present

- name: install typescript-language-server package
  become_user: '{{username}}'
  community.general.npm:
    name: typescript-language-server
    global: yes
    executable: '{{npm_executable}}'
    state: present

- name: install eslint package
  become_user: '{{username}}'
  community.general.npm:
    name: eslint
    global: yes
    executable: '{{npm_executable}}'
    state: present

- name: install prettier package
  become_user: '{{username}}'
  community.general.npm:
    name: 'prettier'
    global: yes
    executable: '{{npm_executable}}'
    state: present

- name: install prettierd package
  become_user: '{{username}}'
  community.general.npm:
    name: '@fsouza/prettierd'
    global: yes
    executable: '{{npm_executable}}'
    state: present

# html css and json
- name: install html, css, and json packages
  become_user: '{{username}}'
  community.general.npm:
    name: 'vscode-langservers-extracted'
    global: yes
    executable: '{{npm_executable}}'
    state: present
