- name: ensure locale is set to {{ config_system_locale }}
  import_tasks: locale.yml

# packages
- name: install packages
  import_tasks: packages.yml

- name: set zsh to be the default shell
  user:
    name: "{{username}}"
    shell: /usr/bin/zsh

# dotfiles
- name: run dotfiles tasks
  import_tasks: dotfiles.yml

# starship
- name: test starship binary exists
  stat:
    path: /usr/local/bin/starship
  register: test_starship_binary

- name: ensure usr local bin is created
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: install starship
  unarchive:
    src: https://github.com/starship/starship/releases/download/v1.11.0/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when: not test_starship_binary.stat.exists

# enable pcspkr device for roland
# allows access to /dev/input/by-path/platform-pcspkr-event-spkr
- name: add '{{username}}' to group realtime
  user:
    name: '{{username}}'
    groups: input
    append: yes

# copy over the gpg config file
- name: ensure gnupg dir created in home directory
  file:
    path: '/home/{{username}}/.gnupg'
    state: directory
    mode: '0755'
    owner: '{{username}}'
    group: '{{username}}'

- name: copy gpg-agent.conf to gnupg directory
  copy:
    src: ./gpg-agent.conf
    dest: '/home/{{username}}/.gnupg/gpg-agent.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
    force: yes
