- name: copy sources.list
  copy:
    src: ./sources.list
    dest: /etc/apt/sources.list
    owner: 'root'
    group: 'root'
    mode: 0644
    force: yes
  when: overwrite_apt_sources is true

- name: copy package preferences
  copy:
    src: ./preferences
    dest: /etc/apt/preferences
    owner: 'root'
    group: 'root'
    mode: 0644
    force: yes


- name: install packages
  apt: 
    update_cache: yes
    pkg:
      - git
      - ssh
      - sudo
      - curl
      - wget
      - python3
      - python3-pip
      - zsh
      - luarocks
      - build-essential
      - cmake
      - ripgrep
      - fd-find
      - htop
      - psmisc
      - fuse
      - pinentry-curses
      - pinentry-tty

- name: check if device is laptop
  shell:
    cmd: 'dmidecode | grep Version'
  changed_when: false
  register: dmidecode_version

- name: install laptop specific packages
  apt:
    update_cache: no
    pkg:
      - firmware-iwlwifi
      - firmware-realtek
      - network-manager
      - acpi
  when: >
    (dmidecode_version.stdout is search('ThinkPad'))
