- name: copy sources.list
  copy:
    src: ./sources.list
    dest: /etc/apt/sources.list
    owner: 'root'
    group: 'root'
    mode: 0644
    force: yes
  when: overwrite_apt_sources is true

- name: copy package preferences
  copy:
    src: ./preferences
    dest: /etc/apt/preferences
    owner: 'root'
    group: 'root'
    mode: 0644
    force: yes


# this fixes some random bug i got on a rpi zero
# cannot hurt to install it on all machines
- name: install acl
  apt: 
    update_cache: yes
    pkg:
      - acl

- name: install packages
  apt: 
    update_cache: yes
    pkg:
      - git
      - ssh
      - sudo
      - curl
      - wget
      - python3
      - python3-pip
      - zsh
      - luarocks
      - build-essential
      - cmake
      - ripgrep
      - fd-find
      - htop
      - psmisc
      - fuse
      - pinentry-curses
      - pinentry-tty

- name: check if device is laptop
  shell:
    cmd: 'dmidecode | grep Version'
  changed_when: false
  ignore_errors: true
  register: dmidecode_version

- name: assume device is a laptop if dmidecode fails
  set_fact:
    is_laptop: true
  when: dmidecode_version.rc != 0

- name: install laptop specific packages
  apt:
    update_cache: no
    pkg:
      - firmware-iwlwifi
      - firmware-realtek
      - network-manager
  when: >
    (dmidecode_version.stdout is search('ThinkPad')) or
    (is_laptop is defined and is_laptop)

- name: Install acpi for x86_64
  apt:
    name: acpi
  when: ansible_architecture == 'x86_64'
