- name: install dependencies
  apt:
    update_cache: yes
    pkg:
      - libwacom-dev
      - libiconv-hook-dev
      - flex
      - texinfo
      - texi2html
      - libxml2-dev
      - libxcb-xkb-dev
      - libgles2
      - libgles-dev
      - doxygen
      - libgudev-1.0-dev
      - libgbm-dev
      - libffi-dev
      - libxkbcommon-dev
      - libudev-dev
      - valgrind
      - ninja-build
      - fontconfig
      - libpng-dev
      - xorg
      - libxext-dev
      - libfreetype6-dev
      - libcairo2
      - libcairo2-dev
      - libgtk-3-0
      - libinput-dev
      - libsystemd-dev
      - libharfbuzz-dev
      - libxft-dev
      - libpango1.0-dev
      - libjson-c-dev
      - libpixman-1-dev

- name: install pip packages
  become_user: '{{username}}'
  pip:
    name:
      - meson
      - pyudev
      - pytest
      - libevdev

- name: install pip packages
  pip:
    name:
      - meson
      - pyudev
      - pytest
      - jinja2
      - markdown
      - markupsafe
      - pygments
      - toml
      - typogrify

- name: create sway build directory
  become_user: '{{username}}'
  file:
    path: '{{sway_dir}}'
    mode: 0775
    owner: '{{username}}'
    group: '{{username}}'
    state: directory

- name: clone sway
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/swaywm/sway.git'
    dest: '{{sway_dir}}/sway'
    version: 'v1.7'

- name: clone wlroots
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/wlroots/wlroots.git'
    dest: '{{sway_dir}}/wlroots'
    version: '0.15'

- name: clone libffi
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/libffi/libffi.git'
    dest: '{{sway_dir}}/libffi'
    version: 'v3.3'

- name: clone wayland
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/wayland/wayland.git'
    dest: '{{sway_dir}}/wayland'
    version: '1.21.0'

- name: clone wayland-protocols
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/wayland/wayland-protocols.git'
    dest: '{{sway_dir}}/wayland-protocols'
    version: '1.28'

- name: clone libevdev
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/libevdev/libevdev.git'
    dest: '{{sway_dir}}/libevdev'
    version: 'libevdev-1.13.0'

- name: clone check
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/libcheck/check.git'
    dest: '{{sway_dir}}/check'
    version: '0.15.2'

- name: clone libinput
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/wayland-project/libinput.git'
    dest: '{{sway_dir}}/libinput'
    version: '1.21.0'

- name: clone libwacom
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/linuxwacom/libwacom.git'
    dest: '{{sway_dir}}/libwacom'
    version: 'libwacom-2.5.0'

- name: clone drm
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/freedesktop/mesa-drm.git'
    dest: '{{sway_dir}}/drm'
    version: 'libdrm-2.4.114'

- name: clone seatd
  become_user: '{{username}}'
  git:
    repo: 'https://git.sr.ht/~kennylevinsen/seatd'
    dest: '{{sway_dir}}/seatd'
    version: '0.7.0'

- name: download bison
  become_user: '{{username}}'
  unarchive:
    src: https://ftp.gnu.org/gnu/bison/bison-3.8.tar.xz
    dest: '{{sway_dir}}'
    remote_src: yes
    creates: '{{sway_dir}}/bison'
  register: download_bison

- name: rename bison directory
  become_user: '{{username}}'
  command: mv {{sway_dir}}/bison-3.8 {{sway_dir}}/bison
  when: download_bison.changed

- name: download mtdev
  become_user: '{{username}}'
  unarchive:
    src: https://bitmath.org/code/mtdev/mtdev-1.1.6.tar.gz
    dest: '{{sway_dir}}'
    remote_src: yes
    creates: '{{sway_dir}}/mtdev'
  register: download_mtdev

- name: rename mtdev directory
  become_user: '{{username}}'
  command: mv {{sway_dir}}/mtdev-1.1.6 {{sway_dir}}/mtdev
  when: download_mtdev.changed

# --------------------------------------------------------------------------------------------------

# bison
- name: build bison (configure and make)
  become_user: '{{username}}'
  shell:
    cmd: './configure && make'
    chdir: '{{sway_dir}}/bison'
  tags: sway-compile

- name: build bison (install)
  shell:
    cmd: 'make install'
    chdir: '{{sway_dir}}/bison'
  tags: sway-compile

# mtdev
- name: build mtdev (configure and make)
  become_user: '{{username}}'
  shell:
    cmd: './configure && make'
    chdir: '{{sway_dir}}/mtdev'
  tags: sway-compile

- name: build mtdev (install)
  shell:
    cmd: 'make install'
    chdir: '{{sway_dir}}/mtdev'
  tags: sway-compile

# check
- name: build check (config)
  become_user: '{{username}}'
  shell:
    cmd: 'autoreconf --install && ./configure && make'
    chdir: '{{sway_dir}}/check'
  tags: sway-compile

- name: build check (install)
  shell:
    cmd: 'make install && ldconfig'
    chdir: '{{sway_dir}}/check'
  tags: sway-compile

# libffi
- name: build libffi (configure)
  become_user: '{{username}}'
  shell:
    cmd: './autogen.sh && ./configure && make'
    chdir: '{{sway_dir}}/libffi'
  tags: sway-compile

- name: build libffi (install)
  shell:
    cmd: 'make install'
    chdir: '{{sway_dir}}/libffi'
  tags: sway-compile

# drm
- name: build drm (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/ --prefix=/usr'
    chdir: '{{sway_dir}}/drm'
  tags: sway-compile

- name: build drm (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/drm'
  tags: sway-compile

# libevdev
- name: build libevdev (configure)
  become_user: '{{username}}'
  shell:
    cmd: './autogen.sh && ./configure && make'
    chdir: '{{sway_dir}}/libevdev'
  tags: sway-compile

- name: build libevdev (install)
  shell:
    cmd: 'make install'
    chdir: '{{sway_dir}}/libevdev'
  tags: sway-compile

  # The order might matter here (Requires testing)
- name: install pip packages
  become_user: '{{username}}'
  pip:
    name:
      - libevdev
  tags: sway-compile

# libwacom
- name: build libwacom (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/'
    chdir: '{{sway_dir}}/libwacom'
  tags: sway-compile

- name: build libwacom (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/libwacom'
  tags: sway-compile

# wayland
- name: build wayland (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/ -Ddocumentation=false'
    chdir: '{{sway_dir}}/wayland'
  tags: sway-compile

- name: build wayland (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/wayland'
  tags: sway-compile

# wayland-protocols
- name: build wayland-protocols (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/'
    chdir: '{{sway_dir}}/wayland-protocols'
  tags: sway-compile

- name: build wayland-protocols (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/wayland-protocols'
  tags: sway-compile

# libinput
- name: build libinput (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/ -Ddebug-gui=false'
    chdir: '{{sway_dir}}/libinput'
  tags: sway-compile

- name: build libinput (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/libinput'
  tags: sway-compile

# seatd
- name: build seatd (configure)
  become_user: '{{username}}'
  shell:
    cmd: > 
      meson setup
      -Dlibseat-builtin=enabled
      -Dlibseat-seatd=enabled
      -Dlibseat-logind=systemd
      --prefix=/usr
      build/
    chdir: '{{sway_dir}}/seatd'
  tags: sway-compile

- name: build seatd (install)
  shell:
    cmd: ninja -C build/ install
    chdir: '{{sway_dir}}/seatd'
  tags: sway-compile

# wlroots
- name: build wlroots (configure)
  become_user: '{{username}}'
  shell:
    cmd: >
      meson setup
      -Drenderers=gles2
      -Dbackends=libinput,drm
      --prefix=/usr
      build/
    chdir: '{{sway_dir}}/wlroots'
  tags: sway-compile

- name: build wlroots (install)
  shell:
    cmd: ninja -C build/ install
    chdir: '{{sway_dir}}/wlroots'
  tags: sway-compile

# sway
- name: build sway (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson setup build/'
    chdir: '{{sway_dir}}/sway'
  tags: sway-compile

- name: build sway (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/sway'
  tags: sway-compile

# group setup
- name: Ensure group "seat" exists
  group:
    name: seat
    state: present
 
- name: adding '{{username}}' to group seat
  user:
    name: '{{username}}'
    groups: seat
    append: yes

# NOTE: to start sway
# dbus-run-session sway

# NOTE: you can find out where stuff is located using commands like this
# sudo ldconfig -p | grep libdrm
