- name: install core packages
  apt:
    update_cache: yes
    pkg:
      - sway

- name: install portals and xwayland
  apt:
    update_cache: no
    pkg:
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xwayland
      - wayland-protocols

- name: install extras
  apt:
    update_cache: no
    pkg:
      - grim
      - wl-clipboard
      - clipman

- name: copy configure laptop display script to sway configuration directory
  copy:
    src: configure-laptop-display.sh
    dest: /usr/local/etc/sway
    mode: 0755

# udev rule to configure screens and desktop background when HDMI plug in or out
- name: Copy on_hdmi_connected.rules to /etc/udev/rules.d/
  copy:
    src: 'on_hdmi_connected.rules'
    dest: /etc/udev/rules.d/on_hdmi_connected.rules
