- name: install dependencies
  apt:
    update_cache: yes
    pkg:
      - libwacom-dev
      - libiconv-hook-dev
      - flex
      - texinfo
      - texi2html
      - libxml2-dev
      - libxcb-xkb-dev
      - libgles2
      - libgles-dev
      - doxygen
      - libgudev-1.0-dev
      - libgbm-dev
      - libffi-dev
      - libxkbcommon-dev
      - libudev-dev
      - valgrind
      - ninja-build
      - fontconfig
      - libpng-dev
      - xorg
      - libxext-dev
      - libfreetype6-dev
      - libcairo2
      - libcairo2-dev
      - libgtk-3-0
      - libinput-dev
      - libsystemd-dev
      - libharfbuzz-dev
      - libxft-dev
      - libpango1.0-dev
      - libjson-c-dev
      - libpixman-1-dev
      - libbison-dev
      - libmtdev-dev
      - check
      - libpciaccess-dev
      - libjansson-dev

- name: Install packages for xwayland
  apt:
    name:
      - x11proto-dev
      - libxkbfile-dev
      - libxfont-dev
      - xfonts-utils
      - libdrm-dev
      - openssl
      - libssl-dev
      - xorg-dev
      - libxshmfence-dev
      - libxcb-composite0-dev
      - libxcb-icccm4-dev
      - libxcb-res0-dev
    update_cache: yes
  when: xwayland == true

- name: install pip packages
  become_user: '{{username}}'
  pip:
    name:
      - meson
      - pyudev
      - pytest
      - libevdev

- name: install pip packages for xwayland
  become_user: '{{username}}'
  pip:
    name:
      - mako
  when: xwayland == true

- name: install pip packages (for root user)
  pip:
    name:
      - meson
      - pyudev
      - pytest
      - jinja2
      - markdown
      - markupsafe
      - pygments
      - toml
      - typogrify

- name: create sway build directory
  become_user: '{{username}}'
  file:
    path: '{{sway_dir}}'
    mode: 0775
    owner: '{{username}}'
    group: '{{username}}'
    state: directory

- name: clone sway
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/swaywm/sway.git'
    dest: '{{sway_dir}}/sway'
    version: 'v1.7'

- name: clone wlroots
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/wlroots/wlroots.git'
    dest: '{{sway_dir}}/wlroots'
    version: '0.15'

- name: clone wayland
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/wayland/wayland.git'
    dest: '{{sway_dir}}/wayland'
    version: '1.21.0'

- name: clone wayland-protocols
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/wayland/wayland-protocols.git'
    dest: '{{sway_dir}}/wayland-protocols'
    version: '1.28'

- name: clone libinput
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/wayland-project/libinput.git'
    dest: '{{sway_dir}}/libinput'
    version: '1.21.0'

- name: clone drm
  become_user: '{{username}}'
  git:
    repo: 'https://github.com/freedesktop/mesa-drm.git'
    dest: '{{sway_dir}}/drm'
    version: 'libdrm-2.4.114'

- name: clone seatd
  become_user: '{{username}}'
  git:
    repo: 'https://git.sr.ht/~kennylevinsen/seatd'
    dest: '{{sway_dir}}/seatd'
    version: '0.7.0'

# xwayland only
- name: Clone libepoxy repository
  become_user: '{{username}}'
  git:
    repo: https://github.com/anholt/libepoxy.git
    dest: '{{sway_dir}}/libepoxy'
    version: '1.5.10'
    depth: 1
  when: xwayland == true

# xwayland only
- name: Clone xorgproto repository
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/xorg/proto/xorgproto.git'
    dest: '{{sway_dir}}/xorgproto'
    version: 'xorgproto-2022.2'
    depth: 1
  when: xwayland == true

# xwayland only
- name: Clone xserver repository
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/xorg/xserver.git'
    dest: '{{sway_dir}}/xserver'
    version: 'xwayland-22.1.5'
    depth: 1
  when: xwayland == true

# xwayland only
- name: Clone libxcvt repository
  become_user: '{{username}}'
  git:
    repo: 'https://gitlab.freedesktop.org/xorg/lib/libxcvt.git'
    dest: '{{sway_dir}}/libxcvt'
    version: 'libxcvt-0.1.2'
    depth: 1
  when: xwayland == true

# xwayland only
- name: create xdg-desktop-portal-wlr sway build directory
  become_user: '{{username}}'
  file:
    path: '{{sway_dir}}/xdg-desktop-portal-wlr'
    mode: 0775
    owner: '{{username}}'
    group: '{{username}}'
    state: directory

# xwayland only
- name: download xdg-desktop-portal-wlr
  become_user: '{{username}}'
  unarchive:
    src: 'https://github.com/emersion/xdg-desktop-portal-wlr/releases/download/v0.6.0/xdg-desktop-portal-wlr-0.6.0.tar.gz'
    dest: '{{sway_dir}}/xdg-desktop-portal-wlr'
    remote_src: yes

# --------------------------------------------------------------------------------------------------

# drm
- name: build drm (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/ --prefix=/usr -Dintel=enabled'
    chdir: '{{sway_dir}}/drm'
  tags: sway-compile

- name: build drm (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/drm'
  tags: sway-compile

# wayland
- name: build wayland (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/ -Ddocumentation=false'
    chdir: '{{sway_dir}}/wayland'
  tags: sway-compile

- name: build wayland (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/wayland'
  tags: sway-compile

# wayland-protocols
- name: build wayland-protocols (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/'
    chdir: '{{sway_dir}}/wayland-protocols'
  tags: sway-compile

- name: build wayland-protocols (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/wayland-protocols'
  tags: sway-compile

# libinput
- name: build libinput (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/ -Ddebug-gui=false'
    chdir: '{{sway_dir}}/libinput'
  tags: sway-compile

- name: build libinput (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/libinput'
  tags: sway-compile

# seatd
- name: build seatd (configure)
  become_user: '{{username}}'
  shell:
    cmd: > 
      meson setup
      -Dlibseat-builtin=enabled
      -Dlibseat-seatd=enabled
      -Dlibseat-logind=systemd
      --prefix=/usr
      build/
    chdir: '{{sway_dir}}/seatd'
  tags: sway-compile

- name: build seatd (install)
  shell:
    cmd: ninja -C build/ install
    chdir: '{{sway_dir}}/seatd'
  tags: sway-compile

# libepoxy (xwayland only)
- name: build libepoxy (configure)
  become_user: '{{username}}'
  command: meson setup build
  args:
    chdir: '{{sway_dir}}/libepoxy'
  when: xwayland == true

- name: build libepoxy (build)
  command: ninja -C build install
  args:
    chdir: '{{sway_dir}}/libepoxy'
  when: xwayland == true

# xorgproto (xwayland only)
- name: build xorgproto (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson setup build/'
    chdir: '{{sway_dir}}/xorgproto'
  when: xwayland == true

- name: build xorgproto (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/xorgproto'
  when: xwayland == true

# libxcvt (xwayland only)
- name: build libxcvt (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson build/'
    chdir: '{{sway_dir}}/libxcvt'
  when: xwayland == true

- name: build libxcvt (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/libxcvt'
  when: xwayland == true

# xserver (xwayland only)
- name: build server (configure)
  become_user: '{{username}}'
  command: meson setup build/
  args:
    chdir: '{{sway_dir}}/xserver'
  when: xwayland == true

- name: build xserver (build)
  command: ninja -C build install
  args:
    chdir: '{{sway_dir}}/xserver'
  when: xwayland == true

# wlroots
- name: build wlroots (configure)
  become_user: '{{username}}'
  shell:
    cmd: >
      meson setup
      -Drenderers=gles2
      -Dbackends=libinput,drm
      --prefix=/usr
      build/
    chdir: '{{sway_dir}}/wlroots'
  tags: sway-compile
  when: xwayland == false

- name: build wlroots (configure) for xwayland
  become_user: '{{username}}'
  shell:
    cmd: >
      meson setup
      -Drenderers=gles2
      -Dbackends=libinput,drm
      -Dxwayland=enabled
      --prefix=/usr
      build/
    chdir: '{{sway_dir}}/wlroots'
  tags: 
    - sway-compile 
  when: xwayland == true

- name: build wlroots (install)
  shell:
    cmd: ninja -C build/ install
    chdir: '{{sway_dir}}/wlroots'
  tags: sway-compile

# sway
- name: build sway (configure)
  become_user: '{{username}}'
  shell:
    cmd: 'meson setup build/'
    chdir: '{{sway_dir}}/sway'
  tags: sway-compile

- name: build sway (install)
  shell:
    cmd: 'ninja -C build/ install'
    chdir: '{{sway_dir}}/sway'
  tags: sway-compile

- name: patch sway default config comment default wallpaper out
  shell:
    cmd: sed -i '/^output/s/^/# /' /usr/local/etc/sway/config

# group setup
- name: Ensure group "seat" exists
  group:
    name: seat
    state: present
 
- name: add '{{username}}' to group seat
  user:
    name: '{{username}}'
    groups: seat
    append: yes

- name: copy configure laptop display script to sway configuration directory
  copy:
    src: configure-laptop-display.sh
    dest: /usr/local/etc/sway
    mode: 0755

# NOTE: to start sway
# dbus-run-session sway

# NOTE: you can find out where stuff is located using commands like this
# sudo ldconfig -p | grep libdrm
