- name: Install packages
  apt:
    update_cache: true
    pkg:
      - alsa-utils
      - pulseaudio
      - pulseaudio-utils
      - libasound2-dev
      - libdbus-1-dev

- name: Ensure group "pipewire" exists
  group:
    name: pipewire
    state: present

- name: Ensure group "realtime" exists
  group:
    name: realtime
    state: present

- name: Add user to pipewire group {{ username }}
  user:
    name: "{{ username }}"
    groups: pipewire
    append: true

- name: Add user to realtime group {{ username }}
  user:
    name: "{{ username }}"
    groups: realtime
    append: true

# ensure build dir is created
- name: Ensure build dir created
  file:
    path: "{{ pipewire_tmp_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"

# pipewire download & extract
- name: Check if Pipewire source exists
  stat:
    path: "{{ pipewire_tmp_dir }}/pipewire-0.3.80.zip"
  register: pipewire_src

- name: Download Pipewire Zip File
  get_url:
    url: "https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.80/pipewire-0.3.80.zip"
    dest: "{{ pipewire_tmp_dir }}/pipewire-0.3.80.zip"
    mode: "0644"
  when: not pipewire_src.stat.exists

- name: Extract Pipewire Zip File
  unarchive:
    src: "{{ pipewire_tmp_dir }}/pipewire-0.3.80.zip"
    dest: "{{ pipewire_tmp_dir }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    remote_src: true

# wireplumber download & extract
- name: Check if wireplumber source exists
  stat:
    path: "{{ pipewire_tmp_dir }}/wireplumber-0.4.14.zip"
  register: wireplumber_src

- name: Download Pipewire Zip File
  get_url:
    url: "https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.14/wireplumber-0.4.14.zip"
    dest: "{{ pipewire_tmp_dir }}/wireplumber-0.4.14.zip"
    mode: "0644"
  when: not wireplumber_src.stat.exists

- name: Extract wireplumber Zip File
  unarchive:
    src: "{{ pipewire_tmp_dir }}/wireplumber-0.4.14.zip"
    dest: "{{ pipewire_tmp_dir }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    remote_src: true

# pipewire build
- name: Check if wireplumber source exists
  stat:
    path: "/usr/bin/pipewire"
  register: pipewire_bin

- name: Build Pipewire (configure)
  become: true
  become_user: "{{ username }}"
  command:
    cmd: "meson setup builddir"
    chdir: "{{ pipewire_tmp_dir }}/pipewire-0.3.80"
  when: not pipewire_bin.stat.exists
  changed_when: true

- name: Build Pipewire (configure)
  become: true
  become_user: "{{ username }}"
  command:
    cmd: "meson configure builddir -Dprefix=/usr"
    chdir: "{{ pipewire_tmp_dir }}/pipewire-0.3.80"
  when: not pipewire_bin.stat.exists
  changed_when: true

- name: Build Pipewire (install)
  command:
    cmd: "meson install -C builddir"
    chdir: "{{ pipewire_tmp_dir }}/pipewire-0.3.80"
  when: not pipewire_bin.stat.exists
  changed_when: true

# wireplumber build
- name: Check if wireplumber source exists
  stat:
    path: "/usr/bin/wireplumber"
  register: wireplumber_bin

- name: Build wireplumber (configure)
  become: true
  become_user: "{{ username }}"
  command:
    cmd: "meson setup --prefix=/usr build"
    chdir: "{{ pipewire_tmp_dir }}/wireplumber-0.4.14"
  register: wireplumber_bin
  changed_when: true

- name: Build wireplumber (configure)
  become: true
  become_user: "{{ username }}"
  command:
    cmd: "meson compile -C build"
    chdir: "{{ pipewire_tmp_dir }}/wireplumber-0.4.14"
  register: wireplumber_bin
  changed_when: true

- name: Build wireplumber (install)
  command:
    cmd: "ninja -C build install"
    chdir: "{{ pipewire_tmp_dir }}/wireplumber-0.4.14"
  register: wireplumber_bin
  changed_when: true
