- hosts: localhost
  connection: local
  become: true
  roles:
    - ./roles/setup
    - ./roles/neovim
    - ./roles/zplug

# - hosts: workstations
#   connection: local
#   become: true
#   roles:
#     - ./roles/setup
#     - ./roles/neovim
