- hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: bao_username
      prompt: "OpenBao username (press enter for hostname)"
      default: "{{ lookup('pipe', 'hostname') }}"
      private: false
    - name: bao_password
      prompt: "OpenBao password"
      private: true
  roles:
    - ../roles/openbao
